name: flutter_photokit_example
description: Demonstrates how to use the flutter_photokit plugin.
version: 1.0.0

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: 1.6.24

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_photokit:
    path: ../

flutter:
  uses-material-design: true
